name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: stepV
        uses: musyoka-morris/action-next-semver@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ steps.stepV.outputs.version }}          

          
  build:
    runs-on: ubuntu-latest
    needs: semver
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mailrelay-smtp-server:$(needs.semver.outputs.version)
          
